-- This method is used when the table is not created earlier and needs to be created. 

SELECT * -- COULMN NAMES
INTO [dbo].[VoteTypes2] -- NEW TABLE NAME
FROM [dbo].[VoteTypes] -- ORIGINAL TABLE NAME
--=====================================================================================
-- SELECT COUNT(1) FROM [dbo].[Movement_Details] WHERE Stamp_Date < '01-01-2014'
INSERT INTO [dbo].[Movement_Details_ARC]
      ([Line_ID]
      ,[Movement_Code]
      ,[Item_Code]
      ,[Org_ID]
      ,[Item_Description]
      ,[Item_Alt_Description]
      ,[Quantity_Level2]
      ,[Quantity_Level3]
      ,[Quantity_BU]
      ,[Quantity_SU]
      ,[Currency_Code]
      ,[Price_Level2]
      ,[Price_Level3]
      ,[Movement_Reason_Code]
      ,[Note]
      ,[Affected_Stock]
      ,[Related_TRX_Code]
      ,[Related_TRX_Line_Code]
      ,[Stock_Quantity]
      ,[Is_Processed]
      ,[Requested_Quantity_BU]
      ,[Approve_User_Code]
      ,[Approve_Date]
      ,[Stamp_Date]
      ,[Movement_Status]
      ,[Quantity_Level1]
      ,[Price_Level1]
      ,[Distribution_Code]
      ,[Distribution_Type]
      ,[Tax_Perc]
      ,[Reason_Code])
     SELECT
       [Line_ID]
      ,[Movement_Code]
      ,[Item_Code]
      ,[Org_ID]
      ,[Item_Description]
      ,[Item_Alt_Description]
      ,[Quantity_Level2]
      ,[Quantity_Level3]
      ,[Quantity_BU]
      ,[Quantity_SU]
      ,[Currency_Code]
      ,[Price_Level2]
      ,[Price_Level3]
      ,[Movement_Reason_Code]
      ,[Note]
      ,[Affected_Stock]
      ,[Related_TRX_Code]
      ,[Related_TRX_Line_Code]
      ,[Stock_Quantity]
      ,[Is_Processed]
      ,[Requested_Quantity_BU]
      ,[Approve_User_Code]
      ,[Approve_Date]
      ,[Stamp_Date]
      ,[Movement_Status]
      ,[Quantity_Level1]
      ,[Price_Level1]
      ,[Distribution_Code]
      ,[Distribution_Type]
      ,[Tax_Perc]
      ,[Reason_Code]
FROM [dbo].[Movement_Details] WHERE Stamp_Date < '01-01-2014'
GO