--******************************************************************************************************
-- CHANGE THE BKP FILE NAMES B4 RUN ********************************************************************************************************

USE [master]
RESTORE DATABASE [BAHRAINIFAD] FROM DISK = N'K:\BKP\BAHRAINIFAD_backup_2015_07_15_041635_8491879.bak' WITH FILE = 1, MOVE N'BAHRAINIFAD' TO N'H:\APP_DATA\BAHRAINIFAD_data.mdf', MOVE N'BAHRAINIFAD_LOG' TO N'I:\APP_LOG\BAHRAINIFAD_log.ldf', NOUNLOAD, REPLACE,STATS = 5
GO

RESTORE DATABASE [BIOSERVER] FROM DISK = N'K:\BKP\BIOSERVER_backup_2015_07_15_041635_9741936.bak' WITH FILE = 1, MOVE N'BIOSERVER' TO N'H:\APP_DATA\BIOSERVER_data.mdf', MOVE N'BIOSERVER_log' TO N'I:\APP_LOG\BIOSERVER_log.ldf', NOUNLOAD, REPLACE,STATS = 5
GO

RESTORE DATABASE [CVIT_RESULT] FROM DISK = N'K:\BKP\CVIT_RESULT_backup_2015_07_15_041635_9741936.bak' WITH FILE = 1, MOVE N'CVIT_RESULT' TO N'H:\APP_DATA\CVIT_RESULT_data.mdf', MOVE N'CVIT_RESULT_log' TO N'I:\APP_LOG\CVIT_RESULT_log.ldf', NOUNLOAD, REPLACE,STATS = 5
GO

RESTORE DATABASE [HISGENX] FROM DISK = N'K:\BKP\HISGENX_backup_2015_07_15_041635_9898224.bak' WITH FILE = 1, MOVE N'HISGENX_DATA' TO N'H:\APP_DATA\HISGENX_data.mdf', MOVE N'HISGENX_INDX' TO N'N:\APP_INDX\HISGENX_INDX.ndf', MOVE N'HISGENX_LOG' TO N'I:\APP_LOG\HISGENX_log.ldf', NOUNLOAD, REPLACE,STATS = 5
GO

RESTORE DATABASE [HISGENX_MEDICALRECORD] FROM DISK = N'K:\BKP\HISGENX_MEDICALRECORD_backup_2015_07_15_041635_9898224.bak' WITH FILE = 1, MOVE N'HISGENX.MEDICALRECORD' TO N'H:\APP_DATA\HISGENX.MEDICALRECORD_data.mdf', MOVE N'HISGENX.MEDICALRECORD_log' TO N'I:\APP_LOG\HISGENX.MEDICALRECORD_log.ldf', NOUNLOAD, REPLACE,STATS = 5
GO

RESTORE DATABASE [HRMS] FROM DISK = N'K:\BKP\HRMS_backup_2015_07_15_041635_9898224.bak' WITH FILE = 1, MOVE N'HRMS_Bah' TO N'H:\APP_DATA\HRMS_DATA.mdf', MOVE N'HRMS_Bah_log' TO N'I:\APP_LOG\HRMS_LOG.ldf', NOUNLOAD, REPLACE,STATS = 5
GO

RESTORE DATABASE [LAB_ORDER] FROM DISK = N'K:\BKP\LAB_ORDER_backup_2015_07_15_041636_0054473.bak' WITH FILE = 1, MOVE N'LAB_ORDER' TO N'H:\APP_DATA\LAB_ORDER_data.mdf', MOVE N'LAB_ORDER_log' TO N'I:\APP_LOG\LAB_ORDER_log.ldf', NOUNLOAD, REPLACE,STATS = 5
GO

RESTORE DATABASE [LAB_RESULT] FROM DISK = N'K:\BKP\LAB_RESULT_backup_2015_07_15_041636_0367150.bak' WITH FILE = 1, MOVE N'LAB_REULT' TO N'H:\APP_DATA\LAB_RESULT_data.mdf', MOVE N'LAB_REULT_log' TO N'I:\APP_LOG\LAB_RESULT_LOG.ldf', NOUNLOAD, REPLACE,STATS = 5
GO

RESTORE DATABASE [PHARMAKON] FROM DISK = N'K:\BKP\PHARMAKON_backup_2015_07_15_041636_0523251.bak' WITH FILE = 1, MOVE N'PHARMAKON' TO N'H:\APP_DATA\PHARMAKON_DATA.mdf', MOVE N'PHARMAKON_log' TO N'I:\APP_LOG\PHARMAKON_LOG.ldf', NOUNLOAD, REPLACE,STATS = 5
GO

RESTORE DATABASE [RIS_ORDER] FROM DISK = N'K:\BKP\RIS_ORDER_backup_2015_07_15_041636_0523251.bak' WITH FILE = 1, MOVE N'RIS_ORDER' TO N'H:\APP_DATA\RIS_ORDER_data.mdf', MOVE N'RIS_ORDER_log' TO N'I:\APP_LOG\RIS_ORDER_LOG.ldf', NOUNLOAD, REPLACE,STATS = 5
GO

RESTORE DATABASE [RIS_RESULT] FROM DISK = N'K:\BKP\RIS_RESULT_backup_2015_07_15_041636_0679524.bak' WITH FILE = 1, MOVE N'RIS_RESULT' TO N'H:\APP_DATA\RIS_RESULT_data.mdf', MOVE N'RIS_RESULT_log' TO N'I:\APP_LOG\RIS_RESULT_log.ldf', NOUNLOAD, REPLACE,STATS = 5
GO

RESTORE DATABASE [SENTRY] FROM DISK = N'K:\BKP\SENTRY_backup_2015_07_15_041636_0679524.bak' WITH FILE = 1, MOVE N'SENTRY_DATA' TO N'H:\APP_DATA\SENTRY_data.mdf', MOVE N'SENTRY_LOG' TO N'I:\APP_LOG\SENTRY_log.ldf', NOUNLOAD, REPLACE,STATS = 5
GO