SET TRANSACTION ISOLATION LEVEL SERIALIZABLE 
ALTER DATABASE distribution SET SINGLE_USER WITH NO_WAIT

ALTER DATABASE distribution SET READ_COMMITTED_SNAPSHOT ON;

ALTER DATABASE distribution SET MULTI_USER WITH NO_WAIT
GO
----------------------------------------------------------------
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE 
ALTER DATABASE [PHARMAKON] SET SINGLE_USER WITH NO_WAIT

ALTER DATABASE [PHARMAKON] SET READ_COMMITTED_SNAPSHOT ON;

ALTER DATABASE [PHARMAKON] SET MULTI_USER WITH NO_WAIT
GO
--------------------------------------------------------------------
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE 
ALTER DATABASE [SENTRY] SET SINGLE_USER WITH NO_WAIT

ALTER DATABASE [SENTRY] SET READ_COMMITTED_SNAPSHOT ON;

ALTER DATABASE [SENTRY] SET MULTI_USER WITH NO_WAIT
GO
--------------------------------------------------------------------
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE 
ALTER DATABASE BAHRAINIFAD SET SINGLE_USER WITH NO_WAIT

ALTER DATABASE BAHRAINIFAD SET READ_COMMITTED_SNAPSHOT ON;

ALTER DATABASE BAHRAINIFAD SET MULTI_USER WITH NO_WAIT
GO
----------------------------------------------------------------------
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE 
ALTER DATABASE HRMS SET SINGLE_USER WITH NO_WAIT

ALTER DATABASE HRMS SET READ_COMMITTED_SNAPSHOT ON;

ALTER DATABASE HRMS SET MULTI_USER WITH NO_WAIT
GO
----------------------------------------------------------------------
select name,is_read_committed_snapshot_on from sys.databases WHERE is_read_committed_snapshot_on =1