SET TRANSACTION ISOLATION LEVEL SERIALIZABLE 
ALTER DATABASE distribution SET SINGLE_USER WITH NO_WAIT

ALTER DATABASE distribution SET READ_COMMITTED_SNAPSHOT ON;

ALTER DATABASE distribution SET MULTI_USER WITH NO_WAIT
GO
