USE [master]
GO
ALTER AVAILABILITY GROUP []
MODIFY REPLICA ON N'<SERVER_NAME>' WITH (SECONDARY_ROLE(READ_ONLY_ROUTING_URL = N'TCP://.com:5022'))
GO
USE [master]
GO
ALTER AVAILABILITY GROUP []
MODIFY REPLICA ON N'<SERVER_NAME>' WITH (SECONDARY_ROLE(READ_ONLY_ROUTING_URL = N'TCP://.com:5022'))
GO
USE [master]
GO
ALTER AVAILABILITY GROUP []
MODIFY REPLICA ON N'<SERVER_NAME>' WITH (PRIMARY_ROLE(READ_ONLY_ROUTING_LIST = (N'<SERVER_NAME>')))
GO
USE [master]
GO
ALTER AVAILABILITY GROUP []
MODIFY REPLICA ON N'<SERVER_NAME>' WITH (PRIMARY_ROLE(READ_ONLY_ROUTING_LIST = (N'<SERVER_NAME>')))
GO