USE [master]
GO

/****** Object:  Database [DBA]    Script Date: 02/12/2021 8:19:54 PM ******/
CREATE DATABASE [DBA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBA', FILENAME = N'D:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DBA.mdf' , SIZE = 13312KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'DBA_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DBA_log.ldf' , SIZE = 11264KB , MAXSIZE = 2048GB , FILEGROWTH = 10240KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBA] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBA] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [DBA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBA] SET  MULTI_USER 
GO

ALTER DATABASE [DBA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBA] SET  READ_WRITE 
GO


