-- THE PRIMARY NODE

BACKUP CERTIFICATE My_SQLRES_ServerCert 
TO FILE = 'F:\data\Cer_My_SQLRES_ServerCert_backup.cer'
WITH PRIVATE KEY (
FILE = 'F:\data\private_key_My_SQLRES_ServerCert_backup.pvk',
ENCRYPTION BY PASSWORD = '7H0pF0$As^kWOP5')
GO

-- TAKE LOG BKP WILL BE RESTORED IN SECONDARY NODE LATER ***
BACKUP LOG AdventureWorksLT2019_CLEAN 
TO DISK = N'c:\SQLServerTools\AdventureWorksLT2019_CLEAN_tde.trn' WITH NOFORMAT, NOINIT,  
NAME = N'AdventureWorks2019_TDE', SKIP, NOREWIND, NOUNLOAD, COMPRESSION, STATS = 10
GO

-- THE SECONDARY NODE ***

--DROP THE CERT, THEN DROP THE MASTER KEY AND Create IT AGAIN!!

-- DROP CERTIFICATE My_SQLRES_ServerCert
-- DROP MASTER KEY
CREATE MASTER KEY ENCRYPTION BY PASSWORD = '5(UmEZ40<49mzy-';
GO
-- Restore the certificate from the BKP taken in 1st step
CREATE CERTIFICATE My_SQLRES_ServerCert 
FROM FILE = 'c:\SQLServerTools\Cer_My_SQLRES_ServerCert_backup.cer'
WITH PRIVATE KEY (
FILE = 'c:\SQLServerTools\private_key_My_SQLRES_ServerCert_backup.pvk',
DECRYPTION BY PASSWORD = '7H0pF0$As^kWOP5')
GO

-- IF THE DB IS IN RESTORING STATE, THEN SKIP THE NEXT COMMAND
ALTER DATABASE AdventureWorksLT2019_CLEAN SET HADR OFF;
GO

-- NOW RESTORE THE LOG BKP TAKEN FROM PRIMARY NODE:
RESTORE LOG [AdventureWorksLT2019_CLEAN]
FROM DISK = N'c:\SQLServerTools\AdventureWorksLT2019_CLEAN_tde.trn' WITH FILE = 1,  
NOUNLOAD, NORECOVERY, REPLACE, STATS = 5
GO

ALTER DATABASE [AdventureWorks2019] SET HADR AVAILABILITY GROUP = [ATEST2];
GO
-- IF ABOVE COMMAND FAILED, JOIN THE DB FROM GUI, IT WILL WORK