USE [master]
GO

/****** This is to deny specific user from modifying database ******/
CREATE SERVER AUDIT [BMB_AUDIT]
TO FILE 
(	FILEPATH = N'D:\Audit\'
	,MAXSIZE = 5 MB
	,MAX_ROLLOVER_FILES = 2147483647
	,RESERVE_DISK_SPACE = ON
)
WITH
(	QUEUE_DELAY = 1000
	,ON_FAILURE = CONTINUE
	,AUDIT_GUID = '7e299022-ef8c-46f2-9b38-01f885bdfcf5'
)
ALTER SERVER AUDIT [BMB_AUDIT] WITH (STATE = ON)
GO
--========================================================================
USE [<DB_NAME>]
GO

CREATE DATABASE AUDIT SPECIFICATION [BMB_AUDIT]
FOR SERVER AUDIT [BMB_AUDIT]
ADD (DELETE ON DATABASE::[<DB_NAME>] BY [<LOGIN_NAME>]),
ADD (INSERT ON DATABASE::[<DB_NAME>] BY [<LOGIN_NAME>]),
ADD (UPDATE ON DATABASE::[<DB_NAME>] BY [<LOGIN_NAME>])
WITH (STATE = ON)

GO
