USE [master]
GO

/****** Object:  Audit [BMB_AUDIT]    Script Date: 31/07/2019 11:56:35 AM ******/
CREATE SERVER AUDIT [BMB_AUDIT]
TO FILE 
(	FILEPATH = N'D:\Audit\'
	,MAXSIZE = 5 MB
	,MAX_ROLLOVER_FILES = 2147483647
	,RESERVE_DISK_SPACE = ON
)
WITH
(	QUEUE_DELAY = 1000
	,ON_FAILURE = CONTINUE
	,AUDIT_GUID = '7e299022-ef8c-46f2-9b38-01f885bdfcf5'
)
ALTER SERVER AUDIT [BMB_AUDIT] WITH (STATE = ON)
GO
--========================================================================
USE [ABP_SFA_BMB]
GO

CREATE DATABASE AUDIT SPECIFICATION [BMB_AUDIT]
FOR SERVER AUDIT [BMB_AUDIT]
ADD (DELETE ON DATABASE::[ABP_SFA_BMB] BY [ALJOMAIHBEV\bmb3]),
ADD (INSERT ON DATABASE::[ABP_SFA_BMB] BY [ALJOMAIHBEV\bmb3]),
ADD (UPDATE ON DATABASE::[ABP_SFA_BMB] BY [ALJOMAIHBEV\bmb3])
WITH (STATE = ON)
GO