-- SELECT * FROM sys.symmetric_keys 
SELECT * FROM SYS.certificates
USE master 
go

CREATE MASTER KEY ENCRYPTION
BY PASSWORD = 'P@ssw0rd'

CREATE CERTIFICATE SSIS
WITH SUBJECT = 'SSIS_CLR'

CREATE SYMMETRIC KEY SSISPassKey
WITH ALGORITHM = TRIPLE_DES ENCRYPTION
BY CERTIFICATE SSIS

OPEN SYMMETRIC KEY SSISPassKey DECRYPTION
BY CERTIFICATE SSIS

CLOSE SYMMETRIC KEY SSISPassKey
GO

GRANT CONTROL ON CERTIFICATE::SSIS TO [<your_sql_service_account>];
GO 

GRANT REFERENCES ON SYMMETRIC KEY::SSISPassKey TO [<your_sql_service_account>];
GO
