RESTORE DATABASE  FROM [_tape] WITH FILE = 1,
MOVE '' TO N'D:\APP_DATA\.mdf',  
MOVE '_log' TO N'L:\APP_LOG\_1.ldf',
NORECOVERY,REPLACE, NOUNLOAD, STATS = 5
GO

RESTORE DATABASE  FROM [_tape] WITH FILE = 1,
MOVE '' TO N'D:\APP_DATA\.mdf',  
MOVE '_log' TO N'L:\APP_LOG\_1.ldf',
NORECOVERY,REPLACE, NOUNLOAD, STATS = 5
GO

RESTORE DATABASE  FROM [_tape] WITH FILE = 1,
MOVE '' TO N'D:\APP_DATA\.mdf',  
MOVE '_log' TO N'L:\APP_LOG\.ldf',
NORECOVERY, REPLACE,NOUNLOAD, STATS = 5
GO
