-- To temporary disable the Mirroring for a specific DB
ALTER DATABASE [ABP_BMB] SET PARTNER SUSPEND;
ALTER DATABASE [ABP_SFA_BMB] SET PARTNER SUSPEND;

ALTER DATABASE [PEPSI] SET PARTNER SUSPEND;