RESTORE LOG ABP_BMB FROM [ABP_BMB] WITH FILE = 1,
MOVE 'ABP_BMB' TO N'D:\APP_DATA\ABP_BMB.mdf',  
MOVE 'ABP_BMB_log' TO N'L:\APP_LOG\ABP_BMB_1.ldf',
RECOVERY,Replace, NOUNLOAD, STATS = 5
GO

RESTORE LOG ABP_SFA_BMB FROM [ABP_SFA_BMB] WITH FILE = 1,
MOVE 'RASHEDKSADB' TO N'D:\APP_DATA\ABP_SFA_BMB.mdf',  
MOVE 'RASHEDKSADB_log' TO N'L:\APP_LOG\ABP_SFA_BMB_1.ldf',
RECOVERY,Replace, NOUNLOAD, STATS = 5
GO

RESTORE LOG PEPSI FROM [PEPSI] WITH FILE = 1,
MOVE 'RASHEDKSADB' TO N'D:\APP_DATA\PEPSI.mdf',  
MOVE 'RASHEDKSADB_log' TO N'L:\APP_LOG\PEPSI_1.ldf',
RECOVERY,Replace, NOUNLOAD, STATS = 5
GO