USE TasheerDBNew
GO
EXEC sp_configure filestream_access_level,2
GO 
RECONFIGURE
GO
ALTER DATABASE TasheerDBNew
ADD FILEGROUP FS_GROUP CONTAINS FILESTREAM 
GO
ALTER DATABASE TasheerDBNew
ADD FILE (NAME = 'TasheerDBNew_FS', 
FILENAME = 'F:\FS\TasheerDBNew_FS')
TO FILEGROUP FS_GROUP
GO
USE [master]
GO
ALTER DATABASE [TasheerDBNew] SET FILESTREAM( NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = N'TasheerDBNew_FS' ) WITH NO_WAIT
GO