/* CONNECT CMD AS ADMIN
*/
net stop MSSQLSERVER -- OR NAMED INSTANCE NAME
net start MSSQLSERVER /f /T3608

sqlcmd -S . -E
-- IF IT IS NAMED INSTANCE THEN sqlcmd -S HOSTNAME\INSTANCE_NAME -E

SELECT NAME FROM SYS.SERVER_AUDITS WHERE IS_STATE_ENABLED = 1
-- THEN
ALTER SERVER AUDIT [AUDIT_NAME] WITH (STATE=OFF)
GO
DROP SERVER AUDIT [AUDIT_NAME]
GO