DBCC CHECKDB WITH NO_INFOMSGS, ALL_ERRORMSGS, TABLERESULTS, MAXDOP = 10;
SELECT * FROM msdb.dbo.suspect_pages 
DBCC UPDATEUSAGE(<>) WITH NO_INFOMSGS
DBCC CHECKDB WITH PHYSICAL_ONLY; -- Best Practice FOR IO & HUGE DATABASES > 1 TB OR RESTORE THE DB & RUN DBCC THERE
DBCC CHECKALLOC

USE MASTER
DBCC CHECKDB (<>, REPAIR_REBUILD);
DBCC CHECKDB ('', REPAIR_FAST);

 /* ALTER database  SET SINGLE_USER with rollback immediate;
 TAKE FULL DB BKP B4 RUNNING THIS:
 DBCC CHECKTABLE('TRX_details',REPAIR_ALLOW_DATA_LOSS) 
 DBCC CHECKDB (STARLIMS_DATA, REPAIR_ALLOW_DATA_LOSS); */

ALTER DATABASE <> SET MULTI_USER

--ALTER DATABASE  SET OFFLINE 

ALTER DATABASE <> SET ONLINE 

-- ALTER DATABASE SET EMERGENCY