-- DB BECOMES IN SUSBECT DUE TO EITHER LOSS OF DATA FILE OR CORRUPTION OF A TRANSACTION LOG.

--1. RESTART THE SQL SERVER SERVICE
-- MAKE SURE THAT THE SQL SERVER SERVICE ACCOUNT HAS ADMIN RIGHTS ON LOCAL SERVER

-- 2. IF DIDN`T WORK, RESTART THE WHOLE SERVER

--3. 
ALTER DATABASE Footprints SET OFFLINE
ALTER DATABASE Footprints SET ONLINE

--4. 
EXEC sp_resetstatus 'Footprints'
ALTER DATABASE Footprints SET SINGLE_USER WITH ROLLBACK IMMEDIATE
ALTER DATABASE Footprints SET OFFLINE
ALTER DATABASE Footprints SET ONLINE

--5. 
ALTER DATABASE Footprints SET EMERGENCY 
DBCC CHECKDB('Footprints')
DBCC CHECKCATALOG ('Footprints')
--DBCC CHECKDB('Footprints',REPAIR_ALLOW_DATA_LOSS) WITH ALL_ERRORMSGS, NO_INFOMSGS;
ALTER DATABASE Footprints SET MULTI_USER