SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
ALTER DATABASE ABP_BMB SET SINGLE_USER WITH rollback immediate
GO
ALTER DATABASE ABP_BMB SET Read_Write WITH rollback immediate
GO 
ALTER DATABASE ABP_BMB SET MULTI_USER WITH rollback immediate
GO

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
ALTER DATABASE ABP_SFA_BMB SET SINGLE_USER WITH rollback immediate
GO
ALTER DATABASE ABP_SFA_BMB SET Read_Write WITH rollback immediate
GO 
ALTER DATABASE ABP_SFA_BMB SET MULTI_USER WITH rollback immediate
GO
--===================================================================
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
ALTER DATABASE PEPSI SET SINGLE_USER WITH rollback immediate
GO
ALTER DATABASE PEPSI SET Read_Write WITH rollback immediate
GO 
ALTER DATABASE PEPSI SET MULTI_USER WITH rollback immediate
GO