RESTORE DATABASE ABP_BMB FROM [ABP_BMB_tape] WITH FILE = 1,
MOVE 'ABP_BMB' TO N'D:\APP_DATA\ABP_BMB.mdf',  
MOVE 'ABP_BMB_log' TO N'L:\APP_LOG\ABP_BMB_1.ldf',
NORECOVERY,REPLACE, NOUNLOAD, STATS = 5
GO

RESTORE DATABASE ABP_SFA_BMB FROM [ABP_SFA_BMB_tape] WITH FILE = 1,
MOVE 'RASHEDKSADB' TO N'D:\APP_DATA\ABP_SFA_BMB.mdf',  
MOVE 'RASHEDKSADB2' TO N'I:\APP_INDX\ABP_SFA_BMB02.ndf',  
MOVE 'RASHEDKSADB3' TO N'D:\APP_DATA\ABP_SFA_BMB03.ndf',  
MOVE 'RASHEDKSADB_log' TO N'L:\APP_LOG\ABP_SFA_BMB_1.ldf',
NORECOVERY,REPLACE, NOUNLOAD, STATS = 5
GO

RESTORE DATABASE PEPSI FROM [PEPSI_tape] WITH FILE = 1,
MOVE 'RASHEDKSADB' TO N'D:\APP_DATA\PEPSI.mdf',  
MOVE 'RASHEDKSADB_log' TO N'L:\APP_LOG\PEPSI_1.ldf',
NORECOVERY, REPLACE,NOUNLOAD, STATS = 5
GO