USE [master]
GO
ALTER DATABASE [ABP_BMB] SET PARAMETERIZATION FORCED WITH NO_WAIT
GO
ALTER DATABASE [ABP_SFA_BMB] SET PARAMETERIZATION FORCED WITH NO_WAIT
GO
ALTER DATABASE PEPSI SET PARAMETERIZATION FORCED WITH NO_WAIT
GO