SELECT  
    T.TABLE_NAME,  
    T.CONSTRAINT_NAME,  
    K.COLUMN_NAME,  
    K.ORDINAL_POSITION  
FROM  
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS T 
    INNER JOIN 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE K 
    ON T.CONSTRAINT_NAME = K.CONSTRAINT_NAME  
WHERE 
    T.CONSTRAINT_TYPE = 'PRIMARY KEY'  
    -- AND T.TABLE_NAME = 'table_name' 
ORDER BY 
    T.TABLE_NAME,
    K.ORDINAL_POSITION