-- 2 disable ALL constraints ON A TABLE (IN CASE OF DELETEING/UPDATING RECORDS FROM TABLES HAS REFERENTIAL INTEGRITY CONSTRAINTS)

ALTER TABLE [dbo].[HIS_InvoiceMain] NOCHECK CONSTRAINT ALL

-- 2 ENABLE THEM
ALTER TABLE [dbo].[HIS_InvoiceMain] CHECK CONSTRAINT ALL