DBCC SQLPERF (LOGSPACE)
DBCC DROPCLEANBUFFERS
DBCC FREEPROCCACHE
DBCC OPENTRAN
DBCC TRACESTATUS
DBCC USEROPTIONS
DBCC CHECKCONSTRAINTS
DBCC CHECKDB
DBCC CHECKFILEGROUP
DBCC DLLNAME (FREE)
DBCC FREESESSIONCACHE
DBCC TRACEON